# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simulator.ui'
#
# Created: Fri Feb 17 23:20:39 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Simulator(object):
    def setupUi(self, Simulator):
        Simulator.setObjectName(_fromUtf8("Simulator"))
        Simulator.resize(858, 743)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(Simulator.sizePolicy().hasHeightForWidth())
        Simulator.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(Simulator)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.cbo_player1 = QtGui.QComboBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbo_player1.sizePolicy().hasHeightForWidth())
        self.cbo_player1.setSizePolicy(sizePolicy)
        self.cbo_player1.setObjectName(_fromUtf8("cbo_player1"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.cbo_player1)
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.cbo_player2 = QtGui.QComboBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbo_player2.sizePolicy().hasHeightForWidth())
        self.cbo_player2.setSizePolicy(sizePolicy)
        self.cbo_player2.setObjectName(_fromUtf8("cbo_player2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.cbo_player2)
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.cbo_player3 = QtGui.QComboBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbo_player3.sizePolicy().hasHeightForWidth())
        self.cbo_player3.setSizePolicy(sizePolicy)
        self.cbo_player3.setObjectName(_fromUtf8("cbo_player3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.cbo_player3)
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.cbo_player4 = QtGui.QComboBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbo_player4.sizePolicy().hasHeightForWidth())
        self.cbo_player4.setSizePolicy(sizePolicy)
        self.cbo_player4.setObjectName(_fromUtf8("cbo_player4"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.cbo_player4)
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.cbo_player5 = QtGui.QComboBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbo_player5.sizePolicy().hasHeightForWidth())
        self.cbo_player5.setSizePolicy(sizePolicy)
        self.cbo_player5.setObjectName(_fromUtf8("cbo_player5"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.cbo_player5)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 2, 1)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_7)
        self.cbo_scoring = QtGui.QComboBox(self.tab)
        self.cbo_scoring.setObjectName(_fromUtf8("cbo_scoring"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.cbo_scoring)
        self.spin_n_games = QtGui.QSpinBox(self.tab)
        self.spin_n_games.setMinimum(1)
        self.spin_n_games.setMaximum(999999999)
        self.spin_n_games.setObjectName(_fromUtf8("spin_n_games"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.spin_n_games)
        self.gridLayout.addLayout(self.formLayout_2, 0, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.chk_preset_wilds = QtGui.QCheckBox(self.groupBox)
        self.chk_preset_wilds.setObjectName(_fromUtf8("chk_preset_wilds"))
        self.horizontalLayout_2.addWidget(self.chk_preset_wilds)
        self.gridLayout.addWidget(self.groupBox, 1, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.comboBox_7 = QtGui.QComboBox(self.tab_2)
        self.comboBox_7.setObjectName(_fromUtf8("comboBox_7"))
        self.verticalLayout_2.addWidget(self.comboBox_7)
        self.widget = QtGui.QWidget(self.tab_2)
        self.widget.setMinimumSize(QtCore.QSize(800, 600))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_2.addWidget(self.widget)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.tab_3)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.txt_log = QtGui.QTextEdit(self.tab_3)
        self.txt_log.setReadOnly(True)
        self.txt_log.setObjectName(_fromUtf8("txt_log"))
        self.horizontalLayout.addWidget(self.txt_log)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btn_go = QtGui.QPushButton(self.centralwidget)
        self.btn_go.setIconSize(QtCore.QSize(32, 32))
        self.btn_go.setObjectName(_fromUtf8("btn_go"))
        self.horizontalLayout_3.addWidget(self.btn_go)
        self.progress_bar = QtGui.QProgressBar(self.centralwidget)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setObjectName(_fromUtf8("progress_bar"))
        self.horizontalLayout_3.addWidget(self.progress_bar)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        Simulator.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Simulator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 858, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        Simulator.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Simulator)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Simulator.setStatusBar(self.statusbar)

        self.retranslateUi(Simulator)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Simulator)

    def retranslateUi(self, Simulator):
        Simulator.setWindowTitle(QtGui.QApplication.translate("Simulator", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Simulator", "Player 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Simulator", "Player 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Simulator", "Player 3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Simulator", "Player 4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Simulator", "Player 5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Simulator", "Number of Games", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Simulator", "Scoring Scheme", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Simulator", "Additional Variants", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_preset_wilds.setToolTip(QtGui.QApplication.translate("Simulator", "When a player picks up a wild, he must immediately assign it a color, which can not be later modified.", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_preset_wilds.setText(QtGui.QApplication.translate("Simulator", "Preset Wilds", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Simulator", "Simulation Setup", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Simulator", "Results", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("Simulator", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_go.setText(QtGui.QApplication.translate("Simulator", "Go!", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Simulator = QtGui.QMainWindow()
    ui = Ui_Simulator()
    ui.setupUi(Simulator)
    Simulator.show()
    sys.exit(app.exec_())

